/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.swingtp2;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.List;
import java.awt.Point;
import java.awt.Shape;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

/**
 *
 * @author tsl4297A
 */
public class Exo1 extends javax.swing.JPanel {

   
    private final ArrayList<Point> pointsXr = new ArrayList<>(); 
    private final ArrayList<Point> pointsYr = new ArrayList<>(); 
    
    private final ArrayList<Point> pointsXb = new ArrayList<>(); 
    private final ArrayList<Point> pointsYb = new ArrayList<>(); 
    
    private int nbLigneRouge = 0;
    private int nbLigneBleu = 0; 
    
    /**
     * Creates new form Exo2
     */
    public Exo1() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g; 
        
        
        g2d.setColor(Color.red);
        for(int i = 0; i < nbLigneRouge; i++) {
            g2d.drawLine(pointsXr.get(i).x, pointsXr.get(i).y, pointsYr.get(i).x, pointsYr.get(i).y);
        }
        
        g2d.setColor(Color.blue);
        for(int i = 0; i < nbLigneBleu; i++) {
            g2d.drawLine(pointsXb.get(i).x, pointsXb.get(i).y, pointsYb.get(i).x, pointsYb.get(i).y);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        int x1 = evt.getX(); 
        int y1 = evt.getY(); 
        if(javax.swing.SwingUtilities.isLeftMouseButton(evt)) {
            pointsXr.add(new Point(x1, y1));
            nbLigneRouge++; 
        } else {
            pointsXb.add(new Point(x1, y1));
            nbLigneBleu++; 
        }
        
        
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        int x2 = evt.getX(); 
        int y2 = evt.getY();
        if(javax.swing.SwingUtilities.isLeftMouseButton(evt)) {
            pointsYr.add(new Point(x2, y2));
        } else {
            pointsYb.add(new Point(x2, y2));
        }
        
        repaint();
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
